### ISSUE TITLE
Why a threadpool?

### ISSUE THREAD

**Issue by DzigaV** [aio-libs/aiocassandra#43]
I'm considering this library for a project. Thank you for creating and maintaining it.

Is there a reason why it uses a threadpool? The Cassandra driver is already async and has a callback interface. Wouldn't it be more performant to create an interface between the Cassandra driver and asyncio futures?

I could probably write this myself, as it should only be a handful of lines of code. But your pagination context manager is something I'd love to take advantage of.

**Comment by hellysmile** [comment]
original cassandra has in master some asyncio support
https://github.com/datastax/python-driver/blob/master/cassandra/io/asyncioreactor.py
BUT!! it still in separate thread, just uses asyncio transport... Which do not gives any actual profit for asyncio-based projects

I think native transport is doable, but defiantly complex.

**Comment by DzigaV** [comment]
I've been trying to write a Tornado wrapper around the Datastax driver's futures, but no joy so far. Maybe the threadpool is the best approach after all 😄

**Comment by DzigaV** [comment]
I've got something working. Could it really be this simple?

```
from tornado.concurrent import Future

def execute_future(self, *args, **kwargs):
    tornado_future = Future()
    cassandra_future = self.execute_async(*args, **kwargs)
    cassandra_future.add_callback(
        lambda result: self._ioloop.add_callback(tornado_future.set_result, result))
    cassandra_future.add_errback(
        lambda error: self._ioloop.add_callback(tornado_future.set_exception, error))
    return tornado_future
```

**Comment by DzigaV** [comment]
@hellysmile I think this is how to do it without run_in_executor. Using Tornado, but should be easy to port to asyncio:

```
from tornado.concurrent import Future

def execute_future(self, *args, **kwargs):
    tornado_future = Future()
    cassandra_future = self.execute_async(*args, **kwargs)
    cassandra_future.add_callback(
        lambda result: self._ioloop.add_callback(tornado_future.set_result, result))
    cassandra_future.add_errback(
        lambda error: self._ioloop.add_callback(tornado_future.set_exception, error))
    return tornado_future
```

**Comment by hellysmile** [comment]
Are You thinking for tornado support? Patches are welcome, but as far as I know asyncio loop is only one loop for Tornado on Python 3, does it makes a lot of sense?

**Comment by DzigaV** [comment]
Yes, Tornado implements asyncio in PY3. I'm familiar with Tornado syntax so continue to use it, however.

The general point of my example is that I don't think it's necessary to use run_in_executor. You can do it using a future and a callback on the asyncio loop. I don't know the equivalent of IOLoop.add_callback in asyncio. I think it's a combination of call_soon_threadsafe and a Partial.
