### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiocassandra#53]
It's erroring out during `dpkg install` of some java-related thing: https://travis-ci.com/aio-libs/aiocassandra/jobs/150197735#L469

**Comment by FedirAlifirenko** [comment]
It looks like the error has been fixed after moving to OpenJDK Java usage
https://github.com/aio-libs/aiocassandra/pull/73
@hellysmile what do you think ?

**Comment by webknjaz** [comment]
Merged
