### ISSUE TITLE
How can I do pagination?

### ISSUE THREAD

**Issue by Artgyk** [aio-libs/aiocassandra#7]
I haven't found any methods for it

**Comment by hellysmile** [comment]
It is do not supported yet, I have some ideas how to implement it, but it is really tricky

**Comment by hellysmile** [comment]
Hey @Artgyk 
Here is implementation of pagination https://github.com/aio-libs/aiocassandra/pull/14
It will be released soon, after some internal review and polishing.
You are more than welcome to test it from `pagination` branch!

**Comment by hellysmile** [comment]
New release will be in 1-2 days, closing this issue
